version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a Node version: 10, 12, 14
        VARIANT: 14
    command: sleep infinity
    ports:
      - 8081:8081
    volumes:
      - ./:/workspace
      - ./npm-docker:/home/node/.npm
